### PR TITLE
Update README.rst with how it related to SMTT

### PR DESCRIPTION
**Pull request by gilinachum**
*Description of changes:* See title.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by satishpasumarthi — APPROVED** [review]
LGTM!

**Review by josephevans — APPROVED** [review]

**Review by josephevans — APPROVED** [review]

**Comment by gilinachum** [comment]
@josephevans could you please merge this? I don't have permission.

**Comment by satishpasumarthi** [comment]
> @josephevans could you please merge this? I don't have permission.

We are making some changes to our CI. This PR will be merged by End of this week.

**Comment by satishpasumarthi** [comment]
Hi @gilinachum , We have addressed other documentation related changes in our PR https://github.com/aws/sagemaker-pytorch-training-toolkit/pull/246 and merged it, closing this PR.

**Pull request closed without merging**
